{{- if .Values.autoscaling.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ci-test.fullname" . }}-pdb
  labels:
    {{- include "ci-test.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "ci-test.selectorLabels" . | nindent 6 }}
{{- end }}

