# Minimal values for ci-test application
replicaCount: 1

image:
  repository: ghcr.io/deviknitkkr/ci-test
  pullPolicy: IfNotPresent
  tag: "0.0.7"

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  sessionAffinity: None

# HPA configuration with custom scaling behavior
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  # Custom scaling behavior - scale up/down based on 30-second windows
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 100  # Can double the number of pods
        periodSeconds: 30
      - type: Pods
        value: 2    # Can add max 2 pods at once
        periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 50   # Can remove 50% of pods
        periodSeconds: 30
      - type: Pods
        value: 1    # Remove max 1 pod at once
        periodSeconds: 30

# Health checks
livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5

# Resource limits
resources:
  limits:
    cpu: 2048m
    memory: 1024Mi
  requests:
    cpu: 1024m
    memory: 512Mi
