# Minimal values for ci-test application
replicaCount: 2

image:
  repository: ghcr.io/deviknitkkr/ci-test
  pullPolicy: IfNotPresent
  tag: "0.0.7"

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  sessionAffinity: None

# Optimized HPA configuration with smooth scaling behavior
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0  # Scale up immediately when needed
      percentPolicy:
        value: 100  # Can double pods quickly
        periodSeconds: 15
      podsPolicy:
        value: 4  # Add up to 4 pods at once during high load
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300  # Wait 5 minutes before scaling down
      percentPolicy:
        value: 10  # Only reduce by 10% at a time
        periodSeconds: 60
      podsPolicy:
        value: 1  # Remove only 1 pod at a time
        periodSeconds: 60

# Health checks
livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

# Optimized resource limits and requests for better load balancing
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 250m  # Lower CPU requests for better distribution
    memory: 512Mi
