
image:
  repository: ghcr.io/deviknitkkr/ci-test
  pullPolicy: IfNotPresent
  tag: "0.1.16"

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

# Ingress configuration
ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: ci-test.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Simple HPA configuration for stable scaling
replicaCount: 1
autoscaling:
  enabled: true
  minReplicas:
  maxReplicas: 10
  targetCPUUtilizationPercentage: 65

# Health checks
livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 40
  periodSeconds: 5

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
  periodSeconds: 5

# High-performance resource configuration for 4k TPS
resources:
  limits:
    memory: 1Gi
  requests:
    cpu: 1000m
    memory: 500Mi
