# Minimal values for ci-test application
replicaCount: 1

image:
  repository: ghcr.io/deviknitkkr/ci-test
  pullPolicy: IfNotPresent
  tag: "0.1.5"

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080

# Simple HPA configuration for stable scaling
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

# Health checks
livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 60

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5

# High-performance resource configuration for 4k TPS
resources:
  limits:
    cpu: 2000m
    memory: 1Gi
  requests:
    cpu: 1000m
    memory: 500Mi
