# Minimal values for ci-test application
replicaCount: 1

image:
  repository: ghcr.io/deviknitkkr/ci-test
  pullPolicy: IfNotPresent
  tag: "0.0.10"

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  sessionAffinity: None

# Simple HPA configuration for stable scaling
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

# Health checks
livenessProbe:
  httpGet:
    path: /ping
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /ping
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 5

# High-performance resource configuration for 4k TPS
resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 1Gi
