name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.actor }}/ci-test

permissions:
  contents: write
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && !contains(github.event.head_commit.message, 'update image tag')
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Determine version
      id: version
      uses: paulhatch/semantic-version@v5.4.0
      with:
        tag_prefix: "v"
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        version_format: "${major}.${minor}.${patch}"
        bump_each_commit: true

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        # Convert repository name to lowercase for container registry
        REPO_LOWER=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
        docker build --platform linux/arm64 -t ${{ env.REGISTRY }}/${REPO_LOWER}:${{ steps.version.outputs.version }} .
        docker tag ${{ env.REGISTRY }}/${REPO_LOWER}:${{ steps.version.outputs.version }} ${{ env.REGISTRY }}/${REPO_LOWER}:latest
        docker push ${{ env.REGISTRY }}/${REPO_LOWER}:${{ steps.version.outputs.version }}
        docker push ${{ env.REGISTRY }}/${REPO_LOWER}:latest

    - name: Update Helm chart
      run: |
        # Convert repository name to lowercase for container registry
        REPO_LOWER=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
        sed -i "s|tag:.*|tag: \"${{ steps.version.outputs.version }}\"|" helm/values.yaml
        sed -i "s|repository:.*|repository: ${{ env.REGISTRY }}/${REPO_LOWER}|" helm/values.yaml
        
    - name: Commit updated Helm chart
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add helm/values.yaml
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Bot: update image tag to ${{ steps.version.outputs.version }}"
          git push
        fi

    - name: Create Git tag
      run: |
        git tag ${{ steps.version.outputs.version_tag }}
        git push origin ${{ steps.version.outputs.version_tag }}

